# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "685f502e6ec3d002ab450ba406abbe58"
name = "node-react-app"
handle = "node-react-app-31"
application_url = "https://parts-secretary-grand-greater.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://parts-secretary-grand-greater.trycloudflare.com/auth/callback", "https://parts-secretary-grand-greater.trycloudflare.com/auth/shopify/callback", "https://parts-secretary-grand-greater.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
